Output .github/assets/demo.gif
Set FontSize 14
Set Width 1200
Set Height 800
Set Theme "Catppuccin Mocha"

Hide
Type "alias kapi='./kapi'"
Enter
Type "clear"
Enter
Show

Sleep 1s
Type "kapi"
Sleep 500ms
Enter

Sleep 2.5s
Enter
Sleep 500ms
Down
Sleep 500ms
Enter

Sleep 500ms
Type "testkapi"
Sleep 500ms
Enter

Sleep 500ms
Enter 2
Sleep 1s
Space
Sleep 500ms
Enter

Sleep 500ms
Down
Sleep 500ms
Enter

Sleep 2s
Enter
Sleep 5s
