#!/bin/sh
set -e

REPO="slouowzee/kapi"
BINARY="kapi"
INSTALL_DIR="/usr/local/bin"

OS=$(uname -s | tr '[:upper:]' '[:lower:]')
case "$OS" in
  darwin)               OS="darwin"  ;;
  linux)                OS="linux"   ;;
  mingw*|msys*|cygwin*) OS="windows" ;;
  *)
    echo "Unsupported OS: $OS"
    exit 1
    ;;
esac

ARCH=$(uname -m)
case "$ARCH" in
  x86_64|amd64)  ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *)
    echo "Unsupported architecture: $ARCH"
    exit 1
    ;;
esac

VERSION=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
  | grep '"tag_name"' \
  | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')

if [ -z "$VERSION" ]; then
  echo "Error: could not fetch latest version from GitHub."
  exit 1
fi

if [ "$OS" = "windows" ]; then
  ASSET="${BINARY}_${OS}_${ARCH}.zip"
else
  ASSET="${BINARY}_${OS}_${ARCH}.tar.gz"
fi

DOWNLOAD_URL="https://github.com/${REPO}/releases/download/${VERSION}/${ASSET}"

echo "Installing ${BINARY} ${VERSION} (${OS}/${ARCH})..."

TMP_DIR=$(mktemp -d)
if ! curl -fsSL "$DOWNLOAD_URL" -o "$TMP_DIR/$ASSET"; then
  echo "Error: download failed from ${DOWNLOAD_URL}"
  rm -rf "$TMP_DIR"
  exit 1
fi

if [ "$OS" = "windows" ]; then
  unzip -q "$TMP_DIR/$ASSET" -d "$TMP_DIR"
  TMP_BIN="$TMP_DIR/${BINARY}.exe"
  DEST="${INSTALL_DIR}/${BINARY}.exe"
else
  tar -xzf "$TMP_DIR/$ASSET" -C "$TMP_DIR"
  TMP_BIN="$TMP_DIR/${BINARY}"
  DEST="${INSTALL_DIR}/${BINARY}"
fi

chmod +x "$TMP_BIN"

if [ -w "$INSTALL_DIR" ]; then
  mv "$TMP_BIN" "$DEST"
else
  echo "Root permissions required to install to ${INSTALL_DIR}."
  sudo mv "$TMP_BIN" "$DEST"
fi
rm -rf "$TMP_DIR"

if [ "$OS" = "darwin" ]; then
  xattr -c "$DEST" 2>/dev/null || true
fi

echo ""
echo "kapi ${VERSION} installed to ${DEST}."

# NOTE: the integration snippet is generated by the freshly installed binary
# itself (kapi shell-init), so it can never drift from what this version
# actually needs — no shell function text is duplicated here.
config_file_for() {
  case "$1" in
    zsh)        echo "$HOME/.zshrc" ;;
    bash)
      if [ "$OS" = "darwin" ]; then
        echo "$HOME/.bash_profile"
      else
        echo "$HOME/.bashrc"
      fi
      ;;
    ksh)        echo "$HOME/.kshrc" ;;
    dash)       echo "$HOME/.profile" ;;
    fish)       echo "$HOME/.config/fish/config.fish" ;;
    nu|nushell) echo "$HOME/.config/nushell/config.nu" ;;
  esac
}

add_to_file() {
  cfg="$1"
  fn="$2"
  if grep -q "kapi shell integration" "$cfg" 2>/dev/null; then
    echo "Shell integration already present in ${cfg}. Nothing to do."
    return
  fi
  mkdir -p "$(dirname "$cfg")"
  printf '\n%s\n' "$fn" >> "$cfg"
  echo "Shell integration added to ${cfg}."
  echo "Run: source ${cfg}"
}

SHELL_NAME=$(basename "${SHELL:-sh}")
SHELL_FN=$("$DEST" shell-init "$SHELL_NAME" 2>/dev/null) || SHELL_FN=""

printf "\nSet up shell integration for automatic cd after scaffold? [Y/n] "
# When piped (curl | bash), stdin is the script itself: read the answer from
# the terminal instead, and fall back to the default without one.
REPLY=""
if [ -t 0 ]; then
  read -r REPLY
elif { : < /dev/tty; } 2>/dev/null; then
  read -r REPLY < /dev/tty
else
  echo ""
fi

case "$REPLY" in
  [Nn]*)
    echo ""
    if [ -n "$SHELL_FN" ]; then
      echo "Skipped. To enable later, add this to your shell config:"
      printf '%s\n' "$SHELL_FN"
    else
      echo "Skipped. Run 'kapi shell-init --help' later to enable automatic cd."
    fi
    ;;
  *)
    if [ -z "$SHELL_FN" ]; then
      echo "Unknown shell: ${SHELL_NAME}."
      echo "Run 'kapi shell-init --help' to see the supported shells and setup instructions."
    else
      CFG=$(config_file_for "$SHELL_NAME")
      if [ -z "$CFG" ]; then
        echo "Unknown shell: ${SHELL_NAME}."
        echo "Add this manually to your shell config:"
        printf '%s\n' "$SHELL_FN"
      else
        add_to_file "$CFG" "$SHELL_FN"
      fi
    fi
    ;;
esac

echo ""
echo "Run 'kapi' to get started."
